Draft for IP camera handling: new module onvif_cam_management + changes in local_ffmpeg_hls Removed some redundant configs from modules configs files (using global configs instead) Improved installation process a bit, more to do there. File some php warnings about everywhere. Moved all model functions from web_index.php to lib_model.php

diff --git a/modules/local_ffmpeg_hls/bash/ffmpeg_init b/modules/local_ffmpeg_hls/bash/ffmpeg_init
--- a/modules/local_ffmpeg_hls/bash/ffmpeg_init
+++ b/modules/local_ffmpeg_hls/bash/ffmpeg_init
@@ -22,14 +22,14 @@
 # License along with this software; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
-#include localdefs
-source $(dirname $0)/localdefs
+#include localdefs (generated by lib_capture at module init)
+source $(dirname $0)/../etc/localdefs
 
 ASSET=$1
 INPUT=$2
 CALLS=$3
 
-MAXCALLS=3 	# sends a mail after 3 fails
+MAXCALLS=3 	# attemps starting the process $MAXCALLS times before considering it failed
 EXISTS_VIDEO=0 		# 1 if ${COMMON_MOVIE_NAME}* exists on EZrecorder
 
 #first clean up eventual movie remaining
@@ -63,7 +63,8 @@ case "$INPUT" in
             mkdir -p $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high
             # streaming is disabled. We prepare high resolution only
             nice $FFMPEG_PATH -f decklink -i 'UltraStudio Mini Recorder@11' -vcodec libx264 -r 25 -crf 28 -profile:v main -acodec libfdk_aac $AC -maxrate 1000k -bufsize 1835k -pix_fmt yuv420p -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high/$COMMON_MOVIE_NAME.m3u8 -vf fps=1 -y -updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
-        fi ;;
+        fi 
+    ;;
     "IntensityShuttle" )
         if [ -e $STREAMING_INFO ]
         then 
@@ -75,19 +76,72 @@ case "$INPUT" in
             mkdir -p $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high
             # streaming is disabled. We prepare high resolution only
             $FFMPEG_PATH -f decklink -i 'Intensity Shuttle@3' -vcodec libx264 -r 25 -crf 18 -profile:v main -acodec libfdk_aac $AC -maxrate 1000k -bufsize 1835k -pix_fmt yuv420p -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high/$COMMON_MOVIE_NAME.m3u8 -vf fps=1 -y -updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
-        fi ;;   
+        fi 
+    ;;   
     "avfoundation" )
         if [ -e $STREAMING_INFO ]
         then 
             mkdir -p $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high
             mkdir -p $MOVIESDIR/${COMMON_MOVIE_NAME}_0/low
             # streaming is enabled. We prepare low and high resolution
-            $FFMPEG_PATH -f avfoundation  -vcodec rawvideo -pixel_format yuyv422 -r '25' -i '0:1' -vcodec libx264 -r 25 -crf 18 -profile:v main -acodec libfdk_aac $AC -maxrate 1000k -bufsize 1835k -pix_fmt yuv420p -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high/$COMMON_MOVIE_NAME.m3u8 -vcodec libx264 -r 10 -crf 18 -acodec libfdk_aac -profile:v baseline -maxrate 256k -bufsize 480k -pix_fmt yuv420p -b:v 128k -b:a 96k $AC -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_0/low/$COMMON_MOVIE_NAME.m3u8 -vf fps=1 -y -updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
+            $FFMPEG_PATH -f avfoundation -vcodec rawvideo -pixel_format yuyv422 -r '25' -i '0:1' -vcodec libx264 -r 25 -crf 18 -profile:v main -acodec libfdk_aac $AC -maxrate 1000k -bufsize 1835k -pix_fmt yuv420p -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high/$COMMON_MOVIE_NAME.m3u8 -vcodec libx264 -r 10 -crf 18 -acodec libfdk_aac -profile:v baseline -maxrate 256k -bufsize 480k -pix_fmt yuv420p -b:v 128k -b:a 96k $AC -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_0/low/$COMMON_MOVIE_NAME.m3u8 -vf fps=1 -y -updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
         else 
             mkdir -p $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high
             # streaming is disabled. We prepare high resolution only
-            $FFMPEG_PATH -f avfoundation  -vcodec rawvideo -pixel_format yuyv422 -r '25' -i '0:1' -vcodec libx264 -r 25 -crf 18 -profile:v main -acodec libfdk_aac $AC -maxrate 1000k -bufsize 1835k -pix_fmt yuv420p -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high/$COMMON_MOVIE_NAME.m3u8 -vf fps=1 -y -updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
-        fi ;;    
+            $FFMPEG_PATH -f avfoundation -vcodec rawvideo -pixel_format yuyv422 -r '25' -i '0:1' -vcodec libx264 -r 25 -crf 18 -profile:v main -acodec libfdk_aac $AC -maxrate 1000k -bufsize 1835k -pix_fmt yuv420p -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high/$COMMON_MOVIE_NAME.m3u8 -vf fps=1 -y -updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
+        fi 
+    ;;    
+    "rtsp" )
+        if [ -z $FFMPEG_RTSP_MEDIA_HIGH_URI ]
+        then
+            echo "ffmpeg_init: FFMPEG_RTSP_MEDIA_HIGH_URI is not defined, cannot continue" >> $EZCASTDIR/var/_log
+            exit 1
+        fi
+
+        if [ -e $STREAMING_INFO ]
+        then 
+            MOVIEDIR_HIGH=$MOVIESDIR/${COMMON_MOVIE_NAME}_0/high
+            MOVIEDIR_LOW=$MOVIESDIR/${COMMON_MOVIE_NAME}_0/low
+            mkdir -p $MOVIEDIR_HIGH
+            mkdir -p $MOVIEDIR_LOW
+            # streaming is enabled. If a low media is defined, copy it from camera stream, else re encode it ourselves
+            # low probsize allow for faster stream start
+            if [ -z $FFMPEG_RTSP_MEDIA_LOW_URI ]
+            then
+                $FFMPEG_PATH -f rtsp -rtsp_transport tcp -probesize 32 -thread_queue_size 127 \
+                    -i $FFMPEG_RTSP_MEDIA_HIGH_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 \
+                    -hls_list_size 0 -hls_wrap 0 -start_number 1 \
+                    $MOVIEDIR_HIGH/$COMMON_MOVIE_NAME.m3u8 -vcodec libx264 \
+                    -r 10 -crf 18 -acodec libfdk_aac -profile:v baseline -maxrate 256k -bufsize 480k \
+                    -pix_fmt yuv420p -b:v 128k -b:a 96k $AC -force_key_frames "expr:gte(t,n_forced*3)" \
+                    -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 \
+                    $MOVIEDIR_LOW/$COMMON_MOVIE_NAME.m3u8 -vf scale=235:157,fps=1 \
+                    -y -updatefirst 1 $THUMBNAIL_PATH \
+                    >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
+            else
+                # High
+                $FFMPEG_PATH -f rtsp -rtsp_transport tcp -probesize 32 -thread_queue_size 127 \
+                -i $FFMPEG_RTSP_MEDIA_HIGH_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 \
+                -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIEDIR_HIGH/$COMMON_MOVIE_NAME.m3u8 \
+                >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
+                # Low, thumbnails are created from this one
+                $FFMPEG_PATH -f rtsp -rtsp_transport tcp -probesize 32 -thread_queue_size 127 \
+                -i $FFMPEG_RTSP_MEDIA_LOW_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 \
+                -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIEDIR_LOW/$COMMON_MOVIE_NAME.m3u8 \
+                -vf scale=235:157,fps=1 -y -updatefirst 1 $THUMBNAIL_PATH \
+                >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID2
+            fi
+        else 
+            # streaming is disabled. We prepare high resolution only
+            mkdir -p $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high
+            $FFMPEG_PATH -f rtsp -rtsp_transport tcp -probesize 32 -thread_queue_size 127 \
+            -i $FFMPEG_RTSP_MEDIA_HIGH_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 \
+            -hls_list_size 0 -hls_wrap 0 -start_number 1 \
+            $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high/$COMMON_MOVIE_NAME.m3u8 -vf scale=235:157,fps=1 \
+            -y -updatefirst 1 $THUMBNAIL_PATH \
+            >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
+        fi 
+    ;;
         # -f decklink = force BMD source
         # -i = input source
         # -vcodec = video codec (H264)
@@ -108,20 +162,19 @@ esac
 
 
 SDAT=`date +"%s"` 	#start date
-WAITING_DELAY=10 	#if the file doesn't exist after 10s, we consider FFMPEG has planted
+WAITING_DELAY=20 	#if the file doesn't exist after 10s, we consider FFMPEG has crashed
 
 # loop while delay hasn't expired and cam file doesn't exist
 while [ $(( `date +"%s"`- $SDAT )) -le $WAITING_DELAY -a \( $EXISTS_VIDEO -eq 0 \) ]
 do 
-	# if video didn't exist yet, checks if it exists now
-	[ $EXISTS_VIDEO -eq 0 ] && test -e $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high/$COMMON_MOVIE_NAME.m3u8 && EXISTS_VIDEO=1;
-	# if cam doesn't exist yet, wait 
-	if [ $EXISTS_VIDEO -eq 0 ]
-	then
-		sleep 1
-	fi
+    # if video didn't exist yet, checks if it exists now
+    [ $EXISTS_VIDEO -eq 0 ] && test -e $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high/${COMMON_MOVIE_NAME}1.ts && EXISTS_VIDEO=1;
+    # if cam doesn't exist yet, wait 
+    if [ $EXISTS_VIDEO -eq 0 ]
+    then
+        sleep 1
+    fi
 done
-
 
 # add entry in log file 
 [ $CALLS -eq 1 ] && echo "********************************************" >> $EZCASTDIR/var/_check_log
diff --git a/modules/local_ffmpeg_hls/bash/ffmpeg_relaunch b/modules/local_ffmpeg_hls/bash/ffmpeg_relaunch
--- a/modules/local_ffmpeg_hls/bash/ffmpeg_relaunch
+++ b/modules/local_ffmpeg_hls/bash/ffmpeg_relaunch
@@ -24,7 +24,7 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
 #include localdefs
-source $(dirname $0)/localdefs
+source $(dirname $0)/../etc/localdefs
 
 INPUT=$1
 MOVIESNB=`ls -la $MOVIESDIR | grep $COMMON_MOVIE_NAME | wc -l  | sed -e 's/^[ \t]*//'`
@@ -72,6 +72,34 @@ case "$INPUT" in
             # streaming is disabled. We prepare high resolution only
             $FFMPEG_PATH -f avfoundation  -vcodec rawvideo -pixel_format yuyv422 -r '25' -i '0:1' -vcodec libx264 -r 25 -crf 18 -profile:v main -acodec libfdk_aac $AC -maxrate 1000k -bufsize 1835k -pix_fmt yuv420p -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number $CURRENT_INDEX $MOVIESDIR/${COMMON_MOVIE_NAME}_$MOVIESNB/high/$COMMON_MOVIE_NAME.m3u8 -vf fps=1 -y -updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
         fi ;;            
+    "rstp" )
+        if [ -z $FFMPEG_RTSP_MEDIA_HIGH_URI ]
+        then
+            echo "ffmpeg_init: FFMPEG_RTSP_MEDIA_HIGH_URI is not defined, cannot continue" >> $EZCASTDIR/var/_log
+            exit 1
+        fi
+
+        if [ -e $STREAMING_INFO ]
+        then 
+            mkdir -p $MOVIESDIR/${COMMON_MOVIE_NAME}_$MOVIESNB/high
+            mkdir -p $MOVIESDIR/${COMMON_MOVIE_NAME}_$MOVIESNB/low 
+            # streaming is enabled. If a low media is defined, copy it from camera stream, else re encode it ourselves
+            # low probsize allow for faster stream start
+            if [ -z $FFMPEG_RTSP_MEDIA_LOW_URI ]
+            then
+                $FFMPEG_PATH -f rtsp -rtsp_transport tcp -probesize 32 -thread_queue_size 127 -i $FFMPEG_RTSP_MEDIA_HIGH_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_$MOVIESNB/high/$COMMON_MOVIE_NAME.m3u8 -vcodec libx264 -r 10 -crf 18 -acodec libfdk_aac -profile:v baseline -maxrate 256k -bufsize 480k -pix_fmt yuv420p -b:v 128k -b:a 96k $AC -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_0/low/$COMMON_MOVIE_NAME.m3u8 -vf scale=235:157,fps=1 -y -updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
+            else
+                # High
+                $FFMPEG_PATH -f rtsp -rtsp_transport tcp -probesize 32 -thread_queue_size 127 -i $FFMPEG_RTSP_MEDIA_HIGH_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_$MOVIESNB/high/$COMMON_MOVIE_NAME.m3u8 </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
+                # Low, thumbnails are created from this one
+                $FFMPEG_PATH -f rtsp -rtsp_transport tcp -probesize 32 -thread_queue_size 127 -i $FFMPEG_RTSP_MEDIA_LOW_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_$MOVIESNB/low/$COMMON_MOVIE_NAME.m3u8 -vf scale=235:157,fps=1 -y -updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID2
+            fi
+        else 
+            # streaming is disabled. We prepare high resolution only
+            mkdir -p $MOVIESDIR/${COMMON_MOVIE_NAME}_$MOVIESNB/high
+            $FFMPEG_PATH -f rtsp -rtsp_transport tcp -probesize 32 -thread_queue_size 127 -i $FFMPEG_RTSP_MEDIA_HIGH_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 $MOVIESDIR/${COMMON_MOVIE_NAME}_0/high/$COMMON_MOVIE_NAME.m3u8 -vf scale=235:157,fps=1 -y -updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $RECORDDIR/ffmpeg.log & echo $! > $FFMPEG_PID
+        fi 
+        ;;
         # -f decklink = force BMD source
         # -i = input source
         # -vcodec = video codec (H264)
