A lot more defensive programming around recording post processing + Lot of new logs to help see what's going on

diff --git a/modules/local_ffmpeg_hls/bash/ffmpeg_process_recording b/modules/local_ffmpeg_hls/bash/ffmpeg_process_recording
--- a/modules/local_ffmpeg_hls/bash/ffmpeg_process_recording
+++ b/modules/local_ffmpeg_hls/bash/ffmpeg_process_recording
@@ -1,27 +1,5 @@
 #!/bin/bash -x
 
-# EZCAST EZrecorder
-#
-# Copyright (C) 2014 Université libre de Bruxelles
-#
-# Written by Michel Jansens <mjansens@ulb.ac.be>
-# 	     Arnaud Wijns <awijns@ulb.ac.be>
-# UI Design by Julien Di Pietrantonio
-#
-# This software is free software; you can redistribute it and/or
-# modify it under the terms of the GNU Lesser General Public
-# License as published by the Free Software Foundation; either
-# version 3 of the License, or (at your option) any later version.
-#
-# This software is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
-# Lesser General Public License for more details.
-#
-# You should have received a copy of the GNU Lesser General Public
-# License along with this software; if not, write to the Free Software
-# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
-
 #process recording saved in a directory in ~/Movies/local_processing/${SDAT}_$COURSE 
 #merge of movie parts + copy cam soundtrack to slide movie
 
@@ -32,20 +10,25 @@ COURSE=$1
 SDAT=$2
 PROCESSING_TOOL=$3
 HANDLE_SOURCE_DIR=$EZCASTDIR/handle_source/$PROCESSING_TOOL
-STORDIR=$RECORDDIR/local_processing/ffmpeg_${SDAT}_$COURSE
+PROCESSINGDIR=$RECORDDIR/local_processing/ffmpeg_${SDAT}_$COURSE
 TOSERVERDIR=$RECORDDIR/upload_to_server/${SDAT}_$COURSE
 CUTLIST_FILE=$EZCASTDIR/var/${SDAT}_$COURSE/_cut_list
 
 echo "command: ffmpeg_process_recording $COURSE $SDAT"
 #merge movies 
 echo "local merge_movies.php<br>";
-$PHP_PATH $HANDLE_SOURCE_DIR/merge_movies.php $STORDIR ${COMMON_MOVIE_NAME} cam.mov $CUTLIST_FILE
+$PHP_PATH $HANDLE_SOURCE_DIR/merge_movies.php $PROCESSINGDIR ${COMMON_MOVIE_NAME} cam.mov $CUTLIST_FILE
+
+if [ $? != 0 ]; then
+    echo "Merge failed, stopping"
+    exit 1
+fi
 
 #now that processing has been done,
 #move the directories in the upload_to_server section
 if [ -d $TOSERVERDIR ]; then
-    mv $STORDIR/* $TOSERVERDIR/.
-    rm -rf $STORDIR
+    mv $PROCESSINGDIR/* $TOSERVERDIR/.
+    rm -rf $PROCESSINGDIR
 else 
-    mv $STORDIR $TOSERVERDIR
+    mv $PROCESSINGDIR $TOSERVERDIR
 fi
