add rtsp to bash

diff --git a/modules/remote_ffmpeg_hls/remote/bash/ffmpeg_init b/modules/remote_ffmpeg_hls/remote/bash/ffmpeg_init
--- a/modules/remote_ffmpeg_hls/remote/bash/ffmpeg_init
+++ b/modules/remote_ffmpeg_hls/remote/bash/ffmpeg_init
@@ -152,6 +152,51 @@ fi
 					-updatefirst 1 $THUMBNAIL_PATH </dev/null >/dev/null 2> $TARGET_DIR/ffmpeg_${CALLS}.log & echo $! > $FFMPEG_PID
 				fi			
             fi ;;
+        "rtsp" )
+            if [ -z $FFMPEG_RTSP_MEDIA_HIGH_URI ]
+            then
+                echo "ffmpeg_init: FFMPEG_RTSP_MEDIA_HIGH_URI is not defined, cannot continue" >> $TARGET_DIR/_log
+                exit 1
+            fi
+
+            if [ -e $STREAMING_INFO ]
+            then 
+                # streaming is enabled. If a low media is defined, copy it from camera stream, else re encode it ourselves
+                if [ -z $FFMPEG_RTSP_MEDIA_LOW_URI ]
+                then
+                    $FFMPEG_PATH -t $LIMIT_DURATION -f rtsp -rtsp_transport tcp -thread_queue_size 127 \
+                        -i $FFMPEG_RTSP_MEDIA_HIGH_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 \
+                        -hls_list_size 0 -hls_wrap 0 -start_number 1 \
+                        $HIGH_DIR/$COMMON_MOVIE_NAME.m3u8 -vcodec libx264 \
+                        -r 10 -crf 18 -acodec libfdk_aac -profile:v baseline -maxrate 256k -bufsize 480k \
+                        -pix_fmt yuv420p -b:v 128k -b:a 96k $AC -force_key_frames "expr:gte(t,n_forced*3)" \
+                        -flags -global_header -hls_time 3 -hls_list_size 0 -hls_wrap 0 -start_number 1 \
+                        $LOW_DIR/$COMMON_MOVIE_NAME.m3u8 -vf scale=235:157,fps=1 \
+                        -y -updatefirst 1 $THUMBNAIL_PATH \
+                        >/dev/null 2> $TARGET_DIR/ffmpeg.log & echo $! > $FFMPEG_PID
+                else
+                    # High
+                    $FFMPEG_PATH -t $LIMIT_DURATION -f rtsp -rtsp_transport tcp -thread_queue_size 127 \
+                    -i $FFMPEG_RTSP_MEDIA_HIGH_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 \
+                    -hls_list_size 0 -hls_wrap 0 -start_number 1 $HIGH_DIR/$COMMON_MOVIE_NAME.m3u8 \
+                    >/dev/null 2> $TARGET_DIR/ffmpeg.log & echo $! > $FFMPEG_PID
+                    # Low, thumbnails are created from this one
+                    $FFMPEG_PATH -t $LIMIT_DURATION -f rtsp -rtsp_transport tcp -thread_queue_size 127 \
+                    -i $FFMPEG_RTSP_MEDIA_LOW_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 \
+                    -hls_list_size 0 -hls_wrap 0 -start_number 1 $LOW_DIR/$COMMON_MOVIE_NAME.m3u8 \
+                    -vf scale=235:157,fps=1 -y -updatefirst 1 $THUMBNAIL_PATH \
+                    >/dev/null 2> $TARGET_DIR/ffmpeg2.log & echo $! > $FFMPEG_PID2
+                fi
+            else 
+                # streaming is disabled. We prepare high resolution only
+                $FFMPEG_PATH -f rtsp -rtsp_transport tcp -thread_queue_size 127 \
+                -i $FFMPEG_RTSP_MEDIA_HIGH_URI -vcodec copy -acodec libfdk_aac $AC -hls_time 3 \
+                -hls_list_size 0 -hls_wrap 0 -start_number 1 \
+                $HIGH_DIR/$COMMON_MOVIE_NAME.m3u8 -vf scale=235:157,fps=1 \
+                -y -updatefirst 1 $THUMBNAIL_PATH \
+                >/dev/null 2> $TARGET_DIR/ffmpeg.log & echo $! > $FFMPEG_PID
+            fi 
+        ;;
          *)
             #no valid input source specified
             exit 1
